version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout

      - run:
          name: Set up SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
            chmod 644 ~/.ssh/id_rsa.pub
            chmod 700 ~/.ssh
            ssh-keyscan -H 13.201.80.196 >> ~/.ssh/known_hosts

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.201.80.196 \<< 'EOF'
              cd /home/ubuntu/ivend-bench/apps/erpnext
              touch test.txt
              # git pull origin main  # or the branch you are deploying from
              # ./deploy_script.sh  # Ensure this script is executable and handles your deployment
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
