version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      
      - run:
          name: Create SSH Directory
          command: mkdir -p ~/.ssh
      
      - add_ssh_keys:
          fingerprints:
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILBXipcex4iY2xbV+pQOEOm8Ro9gUxeg/G6E0quolncq circleci-newdeploy"
      
      - run:
          name: Add SSH Host
          command: |
            ssh-keyscan -H 13.201.80.196 >> ~/.ssh/known_hosts
      
      - run:
          name: Create File on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@y13.201.80.196 \<< EOF
            cd /home/ubuntu
            touch test.txt
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
