version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: develop
