version: 2.1

jobs:
  deploy:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout

      - run:
          name: Install essential packages
          command: |
            export DEBIAN_FRONTEND=noninteractive
            echo "tzdata tzdata/Areas select Etc" | debconf-set-selections
            echo "tzdata tzdata/Zones/Etc select UTC" | debconf-set-selections
            apt-get update && \
            apt-get install --yes --no-install-suggests --no-install-recommends \
            build-essential \
            git \
            mariadb-client \
            libmariadb-dev \
            pv \
            ntp \
            wget \
            curl \
            supervisor \
            file \
            openssh-server \
            nano \
            vim \
            less \
            htop \
            iputils-ping \
            telnet \
            software-properties-common \
            gnupg \
            libpango-1.0-0 \
            libharfbuzz0b \
            libpangoft2-1.0-0 \
            libpangocairo-1.0-0 \
            ca-certificates \
            fontconfig \
            libfreetype6 \
            libjpeg-turbo8 \
            libpng16-16 \
            libx11-6 \
            libxcb1 \
            libxext6 \
            libxrender1 \
            xfonts-75dpi \
            xfonts-base \
            gcc \
            libcups2-dev \
            libmagic1 && \
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Install Redis
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && \
            apt-get install --yes --no-install-suggests --no-install-recommends redis-server && \
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Install Python 3.11
          command: |
            export DEBIAN_FRONTEND=noninteractive
            add-apt-repository ppa:deadsnakes/ppa && \
            apt-get update && \
            apt-get install --yes --no-install-suggests --no-install-recommends python3.11 python3.11-dev python3.11-venv python3.11-distutils && \
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Install wkhtmltopdf
          command: |
            wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb && \
            apt-get install -f ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb && \
            rm wkhtmltox_0.12.6.1-2.jammy_amd64.deb

      - run:
          name: Install Frappe Fonts
          command: |
            git clone --progress --depth 1 https://github.com/frappe/fonts.git /tmp/fonts && \
            rm -rf /etc/fonts && \
            mv /tmp/fonts/etc_fonts /etc/fonts && \
            rm -rf /usr/share/fonts && \
            mv /tmp/fonts/usr_share_fonts /usr/share/fonts && \
            rm -rf /tmp/fonts && \
            fc-cache -fv

      - run:
          name: Install Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash && \
            export NVM_DIR="$HOME/.nvm" && \
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && \
            nvm install 18.16.0 && \
            nvm use 18.16.0 && \
            nvm alias default 18.16.0 && \
            nvm cache clear

      - run:
          name: Install Yarn
          command: |
            export NVM_DIR="$HOME/.nvm" && \
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && \
            npm install -g yarn

      - run:
          name: Install pip for Python 3.11
          command: |
            wget https://bootstrap.pypa.io/get-pip.py && python3.11 get-pip.py && rm get-pip.py

      - run:
          name: Install Bench
          command: |
            python3.11 -m pip install --upgrade frappe-bench==5.22.6

      - run:
          name: Create SSH Directory
          command: mkdir -p ~/.ssh

      - add_ssh_keys:
          fingerprints:
            - "SHA256:uDoegTrVGuEQAV3JdOekUkvJX0Y8QXuBCvys3ScnLGY"

      - run:
          name: Add SSH Host
          command: |
            ssh-keyscan -H 3.110.151.234 >> ~/.ssh/known_hosts

      - run:
          name: Update the erpnext_app
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@3.110.151.234 \<< EOF
            cd /home/ubuntu/ivend-bench/apps/erpnext
            git pull upstream develop
            bench setup requirements
            bench --site circleciproject.com migrate
            bench build
            bench restart
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
