version: 2.1

jobs:
  deploy:
    docker:
      image: cimg/base:current-22.04
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "$SSH_PUBLIC_KEY"

      - run:
          name: Deploy to EC2
          command: |
            ssh ubuntu@13.201.80.196 "touch test.txt"

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
