version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout

      - run:
          name: Set up SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      - run:
          name: Deploy to EC2
          command: |
            ssh -i ~/.ssh/id_rsa ubuntu@13.201.80.196 "touch test.txt"

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
