version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout

      - run:
          name: Deploy to EC2
          command: |
            ssh -i $SSH_PRIVATE_KEY ubuntu@13.201.80.196 "touch test.txt"

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
