version: 2.1

jobs:
  deploy:
    machine:
      - image: ubuntu:22.04
    steps:
      - checkout
      
      - run:
          name: Create SSH Directory
          command: mkdir -p ~/.ssh
      
      - add_ssh_keys:
          fingerprints:
            - "SHA256:uDoegTrVGuEQAV3JdOekUkvJX0Y8QXuBCvys3ScnLGY"
      
      - run:
          name: Add SSH Host
          command: |
            ssh-keyscan -H 65.1.147.86 >> ~/.ssh/known_hosts
      
      - run:
          name: Create File on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@y65.1.147.86 << EOF
            cd /home/ubuntu
            touch test.txt
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
