version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.20.4
    steps:
      - checkout

      - run:
          name: Install SSH Client
          command: |
            sudo apt-get update && sudo apt-get install -y openssh-client
      
      - run:
          name: Create SSH Directory
          command: sudo mkdir -p ~/.ssh
      
      - add_ssh_keys:
          fingerprints:
            - "SHA256:uDoegTrVGuEQAV3JdOekUkvJX0Y8QXuBCvys3ScnLGY"
      
      - run:
          name: Add SSH Host
          command: |
            ssh-keyscan -H 65.1.147.86 >> ~/.ssh/known_hosts
      
      - run:
          name: Update the erpnext_app
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@65.1.147.86 \<< EOF
            cd /home/ubuntu/ivend-bench/apps/erpnext
            git pull upstream develop
            sudo chmod +x ./update_app.sh
            ./update_app.sh
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
